# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be37c51df0ab1cebe423f38f529778f19edb867fe1cd3468a640f00f145587d2823b5f1d050e2c80d921884ae498919cedc8f46577d3fa8d1a1b07bf3a0aa99e

test:
  secret_key_base: 2dabdeb53b9e02d306d804359da522dbcd1d58a59f6cf3134701bee656b4e733208ee82895222f433938dcb5529a82c1416c180665871e946b606ca30593b952

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
